# (C) Copyright 2025, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

from datetime import datetime, timezone

from action import (
    TestActionConnect,
    TestActionDisconnect,
    TestActionFetchRESTData,
    TestActionSleep,
    TestActionTransmitMQTTData,
)
from case import TestCase
from qemu_commands import DType

test_case_individual_datastream_transmission = TestCase(
    "data-transmission",
    [
        TestActionConnect(timeout=30),
        TestActionSleep(seconds=2),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/binaryblob_endpoint",
            b"binblob",
            DType.ASTARTE_MAPPING_TYPE_BINARYBLOB,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/binaryblobarray_endpoint",
            [b"bin", b"blob"],
            DType.ASTARTE_MAPPING_TYPE_BINARYBLOBARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/boolean_endpoint",
            True,
            DType.ASTARTE_MAPPING_TYPE_BOOLEAN,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/booleanarray_endpoint",
            [True, False, True],
            DType.ASTARTE_MAPPING_TYPE_BOOLEANARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/datetime_endpoint",
            datetime(1994, 3, 25, 13, 32, 0, tzinfo=timezone.utc),
            DType.ASTARTE_MAPPING_TYPE_DATETIME,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/datetimearray_endpoint",
            [
                datetime(1994, 3, 25, 13, 32, 0, tzinfo=timezone.utc),
                datetime(2012, 2, 5, 13, 32, 0, tzinfo=timezone.utc),
            ],
            DType.ASTARTE_MAPPING_TYPE_DATETIMEARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/double_endpoint",
            42.5,
            DType.ASTARTE_MAPPING_TYPE_DOUBLE,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/doublearray_endpoint",
            [42.5, 32.12, 0.0, 2.0],
            DType.ASTARTE_MAPPING_TYPE_DOUBLEARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/integer_endpoint",
            10,
            DType.ASTARTE_MAPPING_TYPE_INTEGER,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/integerarray_endpoint",
            [10, 133, 2, 0],
            DType.ASTARTE_MAPPING_TYPE_INTEGERARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/longinteger_endpoint",
            2**34,
            DType.ASTARTE_MAPPING_TYPE_LONGINTEGER,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/longintegerarray_endpoint",
            [2**34, 0, 2**12],
            DType.ASTARTE_MAPPING_TYPE_LONGINTEGERARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/string_endpoint",
            "hello world",
            DType.ASTARTE_MAPPING_TYPE_STRING,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionTransmitMQTTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "/stringarray_endpoint",
            ["hello", " ", "world", "!"],
            DType.ASTARTE_MAPPING_TYPE_STRINGARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionSleep(seconds=1),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "binaryblob_endpoint",
            b"binblob",
            DType.ASTARTE_MAPPING_TYPE_BINARYBLOB,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "binaryblobarray_endpoint",
            [b"bin", b"blob"],
            DType.ASTARTE_MAPPING_TYPE_BINARYBLOBARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "boolean_endpoint",
            True,
            DType.ASTARTE_MAPPING_TYPE_BOOLEAN,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "booleanarray_endpoint",
            [True, False, True],
            DType.ASTARTE_MAPPING_TYPE_BOOLEANARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "datetime_endpoint",
            datetime(1994, 3, 25, 13, 32, 0, tzinfo=timezone.utc),
            DType.ASTARTE_MAPPING_TYPE_DATETIME,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "datetimearray_endpoint",
            [
                datetime(1994, 3, 25, 13, 32, 0, tzinfo=timezone.utc),
                datetime(2012, 2, 5, 13, 32, 0, tzinfo=timezone.utc),
            ],
            DType.ASTARTE_MAPPING_TYPE_DATETIMEARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "double_endpoint",
            42.5,
            DType.ASTARTE_MAPPING_TYPE_DOUBLE,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "doublearray_endpoint",
            [42.5, 32.12, 0.0, 2.0],
            DType.ASTARTE_MAPPING_TYPE_DOUBLEARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "integer_endpoint",
            10,
            DType.ASTARTE_MAPPING_TYPE_INTEGER,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "integerarray_endpoint",
            [10, 133, 2, 0],
            DType.ASTARTE_MAPPING_TYPE_INTEGERARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "longinteger_endpoint",
            2**34,
            DType.ASTARTE_MAPPING_TYPE_LONGINTEGER,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "longintegerarray_endpoint",
            [2**34, 0, 2**12],
            DType.ASTARTE_MAPPING_TYPE_LONGINTEGERARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "string_endpoint",
            "hello world",
            DType.ASTARTE_MAPPING_TYPE_STRING,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionFetchRESTData(
            "org.astarteplatform.end-to-end.DeviceDatastream",
            "stringarray_endpoint",
            ["hello", " ", "world", "!"],
            DType.ASTARTE_MAPPING_TYPE_STRINGARRAY,
            datetime(2025, 4, 26, 13, 32, 0, tzinfo=timezone.utc),
        ),
        TestActionSleep(seconds=2),
        TestActionDisconnect(timeout=30),
        TestActionSleep(seconds=2),
    ],
)
