name: Docs generation for Github Pages

on:
  push:
    paths:
    # Headers
    - 'include/*'
    # Doc updates
    - 'doc/*'
    # The action itself
    - '.github/workflows/docs-workflow.yaml'
    branches:
    # Create the docs only when it matters
    - 'master'
    - 'release-*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    # Checkout the source
    - uses: actions/checkout@v3
      with:
        path: astarte-device-sdk-esp32
    # Checkout the docs repository
    - uses: actions/checkout@v3
      with:
        repository: astarte-platform/docs
        ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
        path: docs
    - name: Install doxygen
      run: |
        sudo apt-get update
        sudo apt-get -y install doxygen
    - name: Build Docs
      working-directory: ./astarte-device-sdk-esp32/doc
      run: doxygen astarte-device-sdk-esp32.doxy
    - name: Copy Docs
      run: |
        export DOCS_DIRNAME="device-sdks/esp32/$(echo ${{ github.ref }} | sed 's,refs/heads/,,' | sed 's/master/snapshot/g' | sed 's/release-//g')/api"
        rm -rf docs/$DOCS_DIRNAME
        mkdir -p docs/$DOCS_DIRNAME
        cp -r astarte-device-sdk-esp32/doc/out/html/* docs/$DOCS_DIRNAME/
    - name: Commit files
      working-directory: ./docs
      run: |
        git config --local user.email "astarte-machine@ispirata.com"
        git config --local user.name "Astarte Bot"
        git add .
        git commit -m "Update ESP32 SDK documentation"
    - name: Push changes
      working-directory: ./docs
      run: |
        git push origin master
